import express from "express";

import docrouter from "../documentation/index.doc.js";
import healthRouter from "./healthRouter.js";
import authRouter from "./authRouter.js";
import userRouter from "./userRouter.js";
import memberRouter from "./memberRouter.js";
import notificationRouter from "./notificationRouter.js";
import reportRouter from "./reportRouter.js";
import departmentRouter from "./departmentRouter.js";
import roleRouter from "./roleRouter.js";
import settingsRouter from "./settingsRouter.js";
import logRouter from "./logRouter.js";
import requisitionRouter from "./requisitionRouter.js";
import specialRequisitionRouter from "./specialRequisitionRouter.js";
import leaveRouter from "./leaveRouter.js";
import leaveScheduleRouter from "./leaveScheduleRouter.js";
import ticketRouter from "./ticketRouter.js";
import communicationRouter from "./communicationRouter.js";
import publicRouter from "./publicRouter.js";
import adsRouter from "./adsRouter.js";
import eventRouter from "./eventRouter.js";
import programRouter from "./programRouter.js";
import galleryRouter from "./galleryRouter.js";
import partnerRouter from "./partnerRouter.js";
import teamRouter from "./teamRouter.js";
import platformRouter from "./platformRouter.js";
import assetRouter from "./assetRouter.js";
import assetTypeRouter from "./assetTypeRouter.js";
import attendanceRouter from "./attendanceRouter.js";
import membershipReportRouter from "./membershipReportRouter.js";
import membershipYearRouter from "./membershipYearRouter.js";
import membershipCategoryRouter from "./membershipCategoryRouter.js";
import subscriberRouter from "./subscriberRouter.js";
import contactMessageRouter from "./contactMessageRouter.js";
import documentRouter from "./documentRouter.js";
import todoRouter from "./todoRouter.js";
import inventoryRouter from "./inventoryRouter.js";
import missionRouter from "./missionRouter.js";
import companyRouter from "./companyRouter.js";
import organizationRouter from "./organizationRouter.js";
import dashboardRouter from "./dashboardRouter.js";
import edNoteRouter from "./edNoteRouter.js";
import edFullAccessRouter from "./edFullAccessRouter.js";
import memberProductRouter from "./memberProductRouter.js";
import membershipSetupRouter from "./membershipSetupRouter.js";
import chatAssistantRouter from "./chatAssistantRouter.js";
import procurementRouter from "./procurementRouter.js";

const router = express.Router();

if (process.env.API_DOCS_ENABLED !== "0" && process.env.API_DOCS_ENABLED !== "false") {
  router.use("/docs", docrouter);
}

router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/members", memberRouter);
router.use("/notifications", notificationRouter);
router.use("/reports", reportRouter);
router.use("/departments", departmentRouter);
router.use("/roles", roleRouter);
router.use("/settings", settingsRouter);
router.use("/logs", logRouter);
router.use("/requisitions", requisitionRouter);
router.use("/special-requisitions", specialRequisitionRouter);
router.use("/leave-requests", leaveRouter);
router.use("/leave-schedule", leaveScheduleRouter);
router.use("/tickets", ticketRouter);
router.use("/communications", communicationRouter);
router.use("/public", publicRouter);
router.use("/ads", adsRouter);
router.use("/events", eventRouter);
router.use("/programs", programRouter);
router.use("/gallery", galleryRouter);
router.use("/partners", partnerRouter);
router.use("/team", teamRouter);
router.use("/platforms", platformRouter);
router.use("/assets", assetRouter);
router.use("/asset-types", assetTypeRouter);
router.use("/attendance", attendanceRouter);
router.use("/membership-reports", membershipReportRouter);
router.use("/membership-years", membershipYearRouter);
router.use("/membership-categories", membershipCategoryRouter);
router.use("/subscribers", subscriberRouter);
router.use("/contact-messages", contactMessageRouter);
router.use("/documents", documentRouter);
router.use("/todos", todoRouter);
router.use("/inventory", inventoryRouter);
router.use("/mission-requests", missionRouter);
router.use("/company", companyRouter);
router.use("/organization", organizationRouter);
router.use("/dashboard", dashboardRouter);
router.use("/ed-notes", edNoteRouter);
router.use("/ed-full-access", edFullAccessRouter);
router.use("/member-products", memberProductRouter);
router.use("/membership-setup", membershipSetupRouter);
router.use("/assistant", chatAssistantRouter);
router.use("/procurements", procurementRouter);

export default router;
